// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbffcfqfsjrcldmeikkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZmZjZnFmc2pyY2xkbWVpa2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODUyNTksImV4cCI6MjA3MTM2MTI1OX0.IcYm_S3oj7JYCK4aNw6rA4qMxd-8QBrlfCFVfZ12uNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});